/qrb_robot_base_manager:
  ros__parameters:
    ultra_enable: true
    rc_enable: true
    motion_tf_enable: false
    test_transport_latency_enable: false
    car_wheel_space: 0.3302
    car_wheel_perimeter: 0.4115
    ultra_quantity: 7
    scale_speed:
    - -1.0
    - -1.0
    scale_speed_odom:
    - -1.0
    - -1.0
